# WHAT DAY OF THE WEEK DO MOST USERS REGISTER ON?
# OBJECTIVE: WE NEED TO FIGURE OUT WHEN TO SCHEDULE AN AD CAMPAIGN
# Most Popular Registration Date

SELECT
    DAYNAME(created_at) AS day,
    COUNT(*) AS total
FROM users
GROUP BY day
ORDER BY total DESC
LIMIT 2;